# @api = http://localhost:4000/api/auth
@api = https://dwfs16-m3s21-ejercicio-auth.onrender.com/api/auth

### sign in
POST {{api}}/login
Content-Type: application/json

{
    "user_name": "DGOMEZ",
    "password": "121212"
}

### sign in
POST {{api}}/register
Content-Type: application/json

{
    "user_name": "DGOMEZ",
    "password": "121212"
}

### renovar token
{{api}}/renew
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0YzE1MzMwMTQ4OGU4Y2QzNTViYzNiZCIsImlhdCI6MTY5MDM5MTM1NCwiZXhwIjoxNjkwNDA1NzU0fQ.1yFfw8Whl3_4v6CJNejU5bsBq5mseM-tPCzdkJlopEI